{
  inputs = {
    chaotic = {
      url = "github:chaotic-cx/nyx/nyxpkgs-unstable";
    };
    home-manager = {
      follows = "chaotic/home-manager";
    };
<<<<<<< HEAD
    "icedos-github:icedos/apps" = {
      url = "github:icedos/apps/372abf9c09f356ebf19e16ffb19734cccb4255bd";
=======
    icedos-apps-0 = {
<<<<<<< HEAD
      url = "github:icedos/apps/2410562ca0e593c732776fcd4728161fa6737cdf";
>>>>>>> 4b1a071 (Update flake.lock)
=======
      url = "github:icedos/apps/5fb2d830d8dc7d88bded0939d5214e8d9d7b935e";
>>>>>>> acdd2d4 (Update flake.lock)
    };
    "icedos-github:icedos/apps-zen-zen" = {
      inputs = {
        nixpkgs = {
          follows = "nixpkgs";
        };
      };
      url = "github:ezKEa/aagl-gtk-on-nix";
    };
<<<<<<< HEAD
    "icedos-github:icedos/desktop" = {
      url = "github:icedos/desktop/c9a6669a249eddc9cbf019d493b382033561dbed";
    };
    "icedos-github:icedos/hardware" = {
      url = "github:icedos/hardware/2acfe7af53b16e883c7553df086e49d9fe13264d";
    };
    "icedos-github:icedos/hyprland" = {
      url = "github:icedos/hyprland/9cf7fdff29d725832148040610da21363fe8c1c9";
=======
    icedos-desktop-0 = {
      url = "github:icedos/desktop/d26f0fdbb23bf7fb81ffd0a57b44649588034e6b";
    };
    icedos-gnome-0 = {
      url = "github:icedos/gnome/16a6fc3084ea50e611bcef13a01a885fbb19016d";
    };
    icedos-hardware-0 = {
      url = "github:icedos/hardware/cd03974bfac4213f4ea84a1ec5b72bd283af9ea8";
>>>>>>> acdd2d4 (Update flake.lock)
    };
    "icedos-github:icedos/providers" = {
      url = "github:icedos/providers/1273fe1a4086fbe2a84436ca1acb350a0020a410";
    };
    "icedos-github:icedos/tweaks" = {
      url = "github:icedos/tweaks/83d42744d78c418a259b8e1c4ae7eba1d3e9eaf5";
    };
    "icedos-github:icedos/users" = {
      url = "github:icedos/users/9ddc3663045cd05e7df3d99844b4b640741fe667";
    };
    nixpkgs = {
      follows = "chaotic/nixpkgs";
    };

  };

  outputs =
    {
      home-manager,
      nixpkgs,
      self,
      ...
    }@inputs:
    let
      system = "x86_64-linux";

      inherit (builtins) fromTOML;
      inherit (lib) fileContents flatten map;
      inherit (pkgs) lib;

      cfg = (fromTOML (fileContents ./config.toml)).icedos;
      pkgs = nixpkgs.legacyPackages.${system};

      icedosLib = import ./lib.nix {
        inherit lib pkgs inputs;
        config = cfg;
        self = ./.;
      };

      externalModulesOutputs = map icedosLib.getExternalModuleOutputs cfg.repositories;

      extraOptions = flatten (map (mod: mod.options) externalModulesOutputs);

      extraNixosModules = flatten (
        map (mod: mod.nixosModules { inherit inputs; }) externalModulesOutputs
      );
    in
    {
      apps.${system}.init = {
        type = "app";
        program = toString (with pkgs; writeShellScript "icedos-flake-init" "exit");
      };

      nixosConfigurations."nixos" = nixpkgs.lib.nixosSystem rec {
        specialArgs = {
          inherit icedosLib inputs;
        };

        modules = [
          # Read configuration location
          (
            { lib, ... }:
            let
              inherit (lib) mkOption types;
            in
            {
              options.icedos.configurationLocation = mkOption {
                type = types.str;
                default = "/home/stef/code/os/os-config";
              };
            }
          )

          # Symlink configuration state on "/run/current-system/source"
          {
            # Source: https://github.com/NixOS/nixpkgs/blob/5e4fbfb6b3de1aa2872b76d49fafc942626e2add/nixos/modules/system/activation/top-level.nix#L191
            system.extraSystemBuilderCmds = "ln -s ${self} $out/source";
          }

          # Internal modules and config
          (
            { lib, ... }:
            let
              inherit (lib) filterAttrs;

              getModules =
                path:
                map (dir: "/${path}/${dir}") (
                  let
                    inherit (lib) attrNames;
                  in
                  attrNames (filterAttrs (n: v: v == "directory") (builtins.readDir path))
                );
            in
            {
              imports = [ ./options.nix ] ++ getModules ./.extra ++ getModules ./.private;
              config.system.stateVersion = "23.05";
            }
          )

          home-manager.nixosModules.home-manager

          { icedos.system.isFirstBuild = false; }

          (
            # Do not modify this file!  It was generated by ‘nixos-generate-config’
            # and may be overwritten by future invocations.  Please make changes
            # to /etc/nixos/configuration.nix instead.
            {
              config,
              lib,
              pkgs,
              modulesPath,
              ...
            }:

            {
              imports = [
                (modulesPath + "/installer/scan/not-detected.nix")
              ];

              boot.initrd.availableKernelModules = [
                "nvme"
                "xhci_pci"
                "ahci"
                "usbhid"
                "usb_storage"
                "sd_mod"
              ];
              boot.initrd.kernelModules = [ ];
              boot.kernelModules = [ "kvm-amd" ];
              boot.extraModulePackages = [ ];

              fileSystems."/" = {
                device = "/dev/disk/by-uuid/875ba1fd-ae85-47ec-beac-ec515e776834";
                fsType = "btrfs";
                options = [ "subvol=@" ];
              };

              boot.initrd.luks.devices."luks-a42d4af1-e764-4d91-acb2-ac735d979a64".device =
                "/dev/disk/by-uuid/a42d4af1-e764-4d91-acb2-ac735d979a64";

              fileSystems."/boot" = {
                device = "/dev/disk/by-uuid/080E-B189";
                fsType = "vfat";
              };

              swapDevices = [ ];

              # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
              # (the default) this is the recommended approach. When using systemd-networkd it's
              # still possible to use this option, but it's recommended to use it in conjunction
              # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
              networking.useDHCP = lib.mkDefault true;
              # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;

              nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
              hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
            }
          )

        ]
        ++ extraOptions
        ++ extraNixosModules;
      };
    };
}
